In [7]:
import pandas as pd
from datasets import load_dataset
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])
df.describe()

                     job_posted_date  salary_year_avg  salary_hour_avg
count                         785741     22003.000000     10662.000000
mean   2023-06-25 16:02:11.860248576    123286.274072        47.016598
min              2023-01-01 00:00:04     15000.000000         8.000000
25%              2023-03-20 10:05:48     90000.000000        27.500000
50%              2023-06-29 06:11:38    115000.000000        45.980000
75%              2023-09-27 01:01:16    150000.000000        61.159996
max              2023-12-31 23:59:58    960000.000000       391.000000
std                              NaN     48312.449482        21.890738

In [14]:
min_salary = df[('salary_year_avg')].idxmin()

In [16]:
df.iloc[min_salary]

job_title_short                                              Data Engineer
job_title                                           Data Engineer - Hadoop
job_location                                                        Brazil
job_via                                                       via LinkedIn
job_schedule_type                                                Full-time
job_work_from_home                                                   False
search_location                                                     Brazil
job_posted_date                                        2023-12-09 10:05:30
job_no_degree_mention                                                 True
job_health_insurance                                                 False
job_country                                                         Brazil
salary_rate                                                           year
salary_year_avg                                                    15000.0
salary_hour_avg                                                        NaN
company_name                                               Net2Source Inc.
job_skills               ['java', 'python', 'oracle', 'aws', 'hadoop', ...
job_type_skills          {'cloud': ['oracle', 'aws'], 'libraries': ['ha...
Name: 665729, dtype: object

In [18]:
df['job_title_short'].value_counts()

job_title_short
Data Analyst                 196075
Data Engineer                186241
Data Scientist               172286
Business Analyst              49063
Software Engineer             44929
Senior Data Engineer          44563
Senior Data Scientist         36957
Senior Data Analyst           29216
Machine Learning Engineer     14080
Cloud Engineer                12331
Name: count, dtype: int64

In [19]:
df['job_title_short'].unique()

array(['Senior Data Engineer', 'Data Analyst', 'Data Engineer',
       'Business Analyst', 'Data Scientist', 'Machine Learning Engineer',
       'Senior Data Analyst', 'Cloud Engineer', 'Senior Data Scientist',
       'Software Engineer'], dtype=object)

In [21]:
df.groupby('job_title_short')

In [23]:
df.groupby('job_title_short')['job_title_short']

In [27]:
df.groupby('job_title_short')['salary_year_avg'].min()

job_title_short
Business Analyst             16500.0
Cloud Engineer               42000.0
Data Analyst                 25000.0
Data Engineer                15000.0
Data Scientist               27000.0
Machine Learning Engineer    30000.0
Senior Data Analyst          30000.0
Senior Data Engineer         35000.0
Senior Data Scientist        45000.0
Software Engineer            28000.0
Name: salary_year_avg, dtype: float64

In [28]:
df.groupby('job_title_short')['salary_year_avg'].median(
)

job_title_short
Business Analyst              85000.0
Cloud Engineer                90000.0
Data Analyst                  90000.0
Data Engineer                125000.0
Data Scientist               127500.0
Machine Learning Engineer    106415.0
Senior Data Analyst          111175.0
Senior Data Engineer         147500.0
Senior Data Scientist        155500.0
Software Engineer             99150.0
Name: salary_year_avg, dtype: float64

In [29]:
df.groupby(['job_title_short', 'job_country'])['salary_year_avg'].median()

job_title_short    job_country
Business Analyst   Afghanistan        NaN
                   Albania            NaN
                   Algeria            NaN
                   Angola             NaN
                   Argentina      71100.0
                                   ...
Software Engineer  Venezuela          NaN
                   Vietnam        53600.0
                   Yemen              NaN
                   Zambia             NaN
                   Zimbabwe           NaN
Name: salary_year_avg, Length: 1387, dtype: float64

In [31]:
df.groupby('job_title_short')['salary_year_avg'].median()

job_title_short
Business Analyst              85000.0
Cloud Engineer                90000.0
Data Analyst                  90000.0
Data Engineer                125000.0
Data Scientist               127500.0
Machine Learning Engineer    106415.0
Senior Data Analyst          111175.0
Senior Data Engineer         147500.0
Senior Data Scientist        155500.0
Software Engineer             99150.0
Name: salary_year_avg, dtype: float64

In [32]:
df.groupby('job_title_short')[['salary_year_avg', 'salary_hour_avg']].median()

                           salary_year_avg  salary_hour_avg
job_title_short
Business Analyst                   85000.0        40.362499
Cloud Engineer                     90000.0        40.000000
Data Analyst                       90000.0        32.615002
Data Engineer                     125000.0        58.500000
Data Scientist                    127500.0        47.500000
Machine Learning Engineer         106415.0        47.535000
Senior Data Analyst               111175.0        47.500000
Senior Data Engineer              147500.0        61.500000
Senior Data Scientist             155500.0        47.620003
Software Engineer                  99150.0        47.560001

In [33]:
df.groupby('job_title_short')['salary_year_avg'].agg(['min', 'max', 'median'])

                               min       max    median
job_title_short
Business Analyst           16500.0  387460.0   85000.0
Cloud Engineer             42000.0  280000.0   90000.0
Data Analyst               25000.0  650000.0   90000.0
Data Engineer              15000.0  525000.0  125000.0
Data Scientist             27000.0  960000.0  127500.0
Machine Learning Engineer  30000.0  325000.0  106415.0
Senior Data Analyst        30000.0  425000.0  111175.0
Senior Data Engineer       35000.0  425000.0  147500.0
Senior Data Scientist      45000.0  890000.0  155500.0
Software Engineer          28000.0  375000.0   99150.0

In [34]:
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

In [35]:
df['job_country'].value_counts()

job_country
United States     206292
India              51088
United Kingdom     40375
France             39922
Germany            27694
                   ...
Guinea                 4
Lesotho                3
Mauritania             3
Bhutan                 3
Maldives               2
Name: count, Length: 160, dtype: int64

In [36]:
df['job_country'].value_counts().head(20)

job_country
United States     206292
India              51088
United Kingdom     40375
France             39922
Germany            27694
Spain              25100
Singapore          23696
Sudan              21781
Netherlands        20631
Italy              17013
Canada             16029
Mexico             15139
Poland             14793
Portugal           14508
Australia          12955
South Africa       12414
Belgium            12078
Philippines        11786
Ireland            11162
Switzerland         9924
Name: count, dtype: int64

In [38]:
df['job_country'].isin(['Brazil']).any()

np.True_

In [39]:
df['job_country'].isin(['North Korea']).any()

np.False_

In [40]:
df['job_country'].isin(['North Korea'])

0         False
1         False
2         False
3         False
4         False
          ...
785736    False
785737    False
785738    False
785739    False
785740    False
Name: job_country, Length: 785741, dtype: bool

In [41]:
us_jobs = df[df['job_country'] == "United States"]

In [43]:
us_jobs

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,None,NaN,NaN,Boehringer Ingelheim,None,None
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,None,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
5,Data Engineer,GCP Data Engineer,Anywhere,via ZipRecruiter,Contractor and Temp work,True,Georgia,2023-11-07 14:01:59,False,False,United States,None,NaN,NaN,smart folks inc,"['python', 'sql', 'gcp']","{'cloud': ['gcp'], 'programming': ['python', '..."
6,Senior Data Engineer,Senior Data Engineer - GCP Cloud,"Dearborn, MI",via LinkedIn,Full-time,False,"Florida, United States",2023-03-27 13:18:18,False,False,United States,None,NaN,NaN,"Miracle Software Systems, Inc","['sql', 'python', 'java', 'sql server', 'gcp',...","{'cloud': ['gcp', 'bigquery'], 'databases': ['..."
9,Data Scientist,Data Scientist II,Anywhere,via ZipRecruiter,Full-time,True,"New York, United States",2023-04-23 13:02:57,False,False,United States,None,NaN,NaN,"Radwell International, LLC","['sql', 'python', 'r', 'mongodb', 'mongodb', '...","{'analyst_tools': ['excel'], 'cloud': ['azure'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785673,Data Scientist,Asset Management Data Scientist,"New York, NY",via Trabajo.org,Full-time,False,"New York, United States",2023-10-16 06:01:53,True,False,United States,None,NaN,NaN,JPMorgan Chase & Co.,None,None
785685,Data Analyst,Data Analyst,"Indianapolis, IN",via Trabajo.org,Full-time,False,"Illinois, United States",2023-07-16 06:01:27,True,False,United States,None,NaN,NaN,"Aara Technologies, Inc","['sql', 'excel']","{'analyst_tools': ['excel'], 'programming': ['..."
785692,Data Scientist,Data Scientist- Hybrid Work Location,"Dayton, OH",via Ai-Jobs.net,Full-time,False,"Illinois, United States",2023-04-21 06:02:31,False,True,United States,year,157500.0,NaN,Tenet3,"['python', 'matlab', 'r']","{'programming': ['python', 'matlab', 'r']}"
785703,Data Analyst,Data Analyst - CRYPTOGRAPHY - Full-time,Anywhere,via Snagajob,Full-time,True,"Texas, United States",2023-01-28 06:02:55,True,False,United States,None,NaN,NaN,Axelon Services Corporation,None,None
785705,Data Analyst,Expert Business Data Analyst - Now Hiring,"Oakland, CA",via Snagajob,Full-time,False,"California, United States",2023-01-09 06:00:25,False,False,United States,None,NaN,NaN,PG&E Corporation,"['sql', 'python', 'tableau']","{'analyst_tools': ['tableau'], 'programming': ..."

In [44]:
us_jobs = us_jobs[us_jobs['salary_hour_avg'].notna()]

In [45]:
us_jobs

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
43,Senior Data Engineer,Sr SQL Database Engineer with Data Warehouse /...,None,via LinkedIn,Contractor,False,"Texas, United States",2023-09-13 13:06:55,True,False,United States,hour,NaN,97.500000,Phaxis,"['sql', 'sql server']","{'databases': ['sql server'], 'programming': [..."
51,Senior Data Engineer,Senior Data Engineer,Anywhere,via LinkedIn,Contractor,True,"Illinois, United States",2023-06-21 13:09:39,False,False,United States,hour,NaN,72.500000,Aditi Consulting,"['python', 'java', 'aws', 'databricks', 'spark']","{'cloud': ['aws', 'databricks'], 'libraries': ..."
253,Data Engineer,Data Engineer,Anywhere,via Upwork,Contractor and Temp work,True,Georgia,2023-11-26 13:54:45,True,False,United States,hour,NaN,88.000000,Upwork,"['sql', 'python', 'java', 'mysql', 'postgresql...","{'cloud': ['aws', 'gcp'], 'databases': ['mysql..."
294,Data Analyst,Business/Data Analyst,"Hartford, CT",via Dice,Contractor,False,"New York, United States",2023-07-03 13:00:08,False,False,United States,hour,NaN,52.500000,"Vector Consulting, Inc",None,None
340,Data Analyst,23-00059 BI Data Analysts + Media experience -...,California,via LinkedIn,Contractor,False,"California, United States",2023-02-28 13:01:46,True,False,United States,hour,NaN,67.500000,"iSpace, Inc.","['go', 'sql', 'aws', 'snowflake', 'tableau', '...","{'analyst_tools': ['tableau', 'looker', 'word'..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
783934,Senior Data Engineer,Senior Data Engineer - Now Hiring,"Rancho Cordova, CA",via Snagajob,Full-time,False,Georgia,2023-08-19 06:44:33,False,True,United States,hour,NaN,53.285000,VSP Vision,"['sql', 'oracle', 'aws', 'snowflake', 'redshif...","{'analyst_tools': ['ssis'], 'cloud': ['oracle'..."
784267,Senior Data Engineer,Senior Lead Data Engineer - Now Hiring,"Fredericksburg, VA",via Snagajob,Full-time and Part-time,False,"California, United States",2023-11-13 06:03:59,False,True,United States,hour,NaN,61.159996,Capital One,"['java', 'scala', 'python', 'nosql', 'sql', 'm...","{'cloud': ['redshift', 'snowflake', 'aws', 'az..."
785111,Senior Data Engineer,"Health and Civil Data Engineer, Senior - Now H...","Bethesda, MD",via Snagajob,Full-time and Part-time,False,Georgia,2023-10-08 06:50:59,False,True,United States,hour,NaN,61.159996,Booz Allen Hamilton,"['python', 'sql', 'scala', 'java', 'shell', 'n...","{'cloud': ['aws', 'azure', 'databricks', 'reds..."
785476,Data Scientist,"Data Scientist, Lead","Washington, DC",via Snagajob,Full-time and Part-time,False,Georgia,2023-11-01 06:58:10,False,True,United States,hour,NaN,47.620003,Booz Allen Hamilton,"['databricks', 'azure', 'aws']","{'cloud': ['databricks', 'azure', 'aws']}"
785492,Data Scientist,Data Scientist,"Arlington, VA",via Snagajob,Full-time and Part-time,False,Georgia,2023-11-01 06:58:02,False,True,United States,hour,NaN,47.620003,Booz Allen Hamilton,"['python', 'r', 'pyspark']","{'libraries': ['pyspark'], 'programming': ['py..."

In [46]:
us_jobs.groupby('job_title_short').count()

,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
job_title_short,,,,,,,,,,,,,,,,
Business Analyst,354,352,354,346,354,354,354,354,354,354,354,0,354,354,297,297
Cloud Engineer,14,14,14,14,14,14,14,14,14,14,14,0,14,14,9,9
Data Analyst,3980,3944,3973,3893,3980,3980,3980,3980,3980,3980,3980,0,3980,3980,3369,3369
Data Engineer,1876,1863,1876,1868,1876,1876,1876,1876,1876,1876,1876,0,1876,1876,1774,1774
Data Scientist,2100,2090,2100,2091,2100,2100,2100,2100,2100,2100,2100,0,2100,2100,1784,1784
Machine Learning Engineer,30,30,30,30,30,30,30,30,30,30,30,0,30,30,26,26
Senior Data Analyst,341,336,341,338,341,341,341,341,341,341,341,0,341,341,312,312
Senior Data Engineer,361,357,361,361,361,361,361,361,361,361,361,0,361,361,349,349
Senior Data Scientist,278,277,278,277,278,278,278,278,278,278,278,0,278,278,250,250
Software Engineer,71,71,71,69,71,71,71,71,71,71,71,0,71,71,61,61

In [51]:
us_jobs.groupby('job_title_short')[['salary_year_avg']].min()

                           salary_year_avg
job_title_short
Business Analyst                       NaN
Cloud Engineer                         NaN
Data Analyst                           NaN
Data Engineer                          NaN
Data Scientist                         NaN
Machine Learning Engineer              NaN
Senior Data Analyst                    NaN
Senior Data Engineer                   NaN
Senior Data Scientist                  NaN
Software Engineer                      NaN

In [53]:
us_jobs.groupby('job_title_short')[['salary_year_avg']].min()

                           salary_year_avg
job_title_short
Business Analyst                       NaN
Cloud Engineer                         NaN
Data Analyst                           NaN
Data Engineer                          NaN
Data Scientist                         NaN
Machine Learning Engineer              NaN
Senior Data Analyst                    NaN
Senior Data Engineer                   NaN
Senior Data Scientist                  NaN
Software Engineer                      NaN

In [54]:
us_jobs = us_jobs[us_jobs['salary_hour_avg'].notna()]

In [55]:
us_jobs.groupby('job_title_short')[['salary_year_avg']].min()

                           salary_year_avg
job_title_short
Business Analyst                       NaN
Cloud Engineer                         NaN
Data Analyst                           NaN
Data Engineer                          NaN
Data Scientist                         NaN
Machine Learning Engineer              NaN
Senior Data Analyst                    NaN
Senior Data Engineer                   NaN
Senior Data Scientist                  NaN
Software Engineer                      NaN

In [1]:
us_jobs.groupby('job_title_short')[['salary_year_avg']].agg(['min', 'max', 'median'])

NameError: name 'us_jobs' is not defined